INDUSTRY_TOP_STOCKS = {
    "Auto Manufacturers": ["MARUTI.NS", "TATAMOTORS.NS", "M&M.NS", "BAJAJ-AUTO.NS", "EICHERMOT.NS"],
    "Auto Parts": ["BOSCHLTD.NS", "MRF.NS", "MOTHERSON.NS", "BALKRISIND.NS", "UNOMINDA.NS"],
    "Banking": ["HDFCBANK.NS", "ICICIBANK.NS", "SBIN.NS", "KOTAKBANK.NS", "AXISBANK.NS"],
    "Banks - Regional": ["IDFCFIRSTB.NS", "FEDERALBNK.NS", "BANDHANBNK.NS", "AUBANK.NS", "PNB.NS"],
    "Chemicals": ["SRF.NS", "PIDILITIND.NS", "AARTIIND.NS", "TATACHEM.NS", "DEEPAKNTR.NS"],
    "Communication Services": ["BHARTIARTL.NS", "IDEA.NS", "TATACOMM.NS", "MTNL.NS"],
    "Construction": ["LT.NS", "GMRINFRA.NS", "NCC.NS", "IRB.NS", "PNCINFRA.NS"],
    "Consumer Defensive": ["ITC.NS", "HINDUNILVR.NS", "NESTLEIND.NS", "BRITANNIA.NS", "DABUR.NS"],
    "Consumer Electronics": ["HAVELLS.NS", "VOLTAS.NS", "DIXON.NS", "CROMPTON.NS", "WHIRLPOOL.NS"],
    "Defense": ["HAL.NS", "BEL.NS", "BDL.NS", "BEML.NS", "MAZDOCK.NS"],
    "Education": ["NIITLTD.NS", "ZEELEARN.NS", "NAVNETEDUL.NS"],
    "Electrical Equipment": ["SIEMENS.NS", "ABB.NS", "CGPOWER.NS", "SUZLON.NS", "BHEL.NS"],
    "Electronic Manufacturers": ["KAYNES.NS", "SYRMA.NS", "AVALON.NS", "CENTUM.NS"],
    "Engineering": ["CUMMINSIND.NS", "THERMAX.NS", "AIAENG.NS", "TRITURBINE.NS"],
    "FMCG": ["ITC.NS", "HINDUNILVR.NS", "TATACONSUM.NS", "GODREJCP.NS", "MARICO.NS"],
    "Financial Services": ["BAJFINANCE.NS", "BAJAJFINSV.NS", "CHOLAFIN.NS", "SHRIRAMFIN.NS", "MUTHOOTFIN.NS"],
    "Credit Services": ["SBICARD.NS", "PAYTM.NS", "PFC.NS", "RECLTD.NS", "IRFC.NS"],
    "Healthcare": ["APOLLOHOSP.NS", "MAXHEALTH.NS", "FORTIS.NS", "GLOBALVECT.NS", "ASTERDM.NS"],
    "Hospitality": ["INDHOTEL.NS", "CHALET.NS", "LEMONTREE.NS", "EIHOTEL.NS"],
    "IT Services": ["TCS.NS", "INFY.NS", "HCLTECH.NS", "WIPRO.NS", "TECHM.NS"],
    "Information Technology Services": ["TCS.NS", "INFY.NS", "HCLTECH.NS", "WIPRO.NS", "LTIM.NS"],
    "Insurance": ["HDFCLIFE.NS", "SBILIFE.NS", "ICICIPRULI.NS", "ICICIGI.NS", "LICINDIA.NS"],
    "Media": ["ZEEL.NS", "SUNTV.NS", "PVRINOX.NS", "NETWORK18.NS", "TV18BRDCST.NS"],
    "Metals & Mining": ["TATASTEEL.NS", "HINDALCO.NS", "COALINDIA.NS", "JSWSTEEL.NS", "VEDL.NS"],
    "Steel": ["TATASTEEL.NS", "JSWSTEEL.NS", "SAIL.NS", "JINDALSTEL.NS", "NMDC.NS"],
    "Oil & Gas": ["RELIANCE.NS", "ONGC.NS", "IOC.NS", "BPCL.NS", "GAIL.NS"],
    "Oil": ["RELIANCE.NS", "ONGC.NS", "OIL.NS", "HINDPETRO.NS", "BPCL.NS"],
    "Packaging": ["UPL.NS", "TCPLPACK.NS", "POLYPLEX.NS", "EPL.NS", "UFO.NS"],
    "Pharmaceuticals": ["SUNPHARMA.NS", "CIPLA.NS", "DRREDDY.NS", "DIVISLAB.NS", "LUPIN.NS"],
    "Power": ["NTPC.NS", "POWERGRID.NS", "TATAPOWER.NS", "ADANIPOWER.NS", "JSWENERGY.NS"],
    "Real Estate": ["DLF.NS", "LODHA.NS", "GODREJPROP.NS", "OBEROIRLTY.NS", "PRESTIGE.NS"],
    "Renewable Energy": ["ADANIGREEN.NS", "SUZLON.NS", "KPIGREEN.NS", "BORORENEW.NS"],
    "Retail": ["TRENT.NS", "AVANTIFEED.NS", "VMART.NS", "DMART.NS"],
    "Software - Infrastructure": ["TCS.NS", "INFY.NS", "HCLTECH.NS", "LTIM.NS", "TECHM.NS"],
    "Software - Application": ["PERSISTENT.NS", "COFORGE.NS", "MPHASIS.NS", "TATAELXSI.NS", "KPITTECH.NS"],
    "Sugar": ["BALRAMCHIN.NS", "RENUKA.NS", "TRIVENI.NS", "EIDPARRY.NS", "DAMPURSUG.NS"],
    "Telecommunications": ["BHARTIARTL.NS", "IDEA.NS", "TATACOMM.NS", "ITI.NS", "ROUTE.NS"],
    "Textiles": ["PAGEIND.NS", "KPRMILL.NS", "WELSPUNIND.NS", "VARDHMAN.NS", "ARVIND.NS"],
    "Utilities": ["NTPC.NS", "POWERGRID.NS", "TATAPOWER.NS", "TORNTPOWER.NS", "CESC.NS"]
}
